### ISSUE TITLE
read failure problem

### ISSUE THREAD

**Issue by RockyLim92** [OpenChannelSSD/liblightnvm#16]
Hi,

I met a problem when i read a single sector using CLI api

I first erased and wrote a virtual block(means the block is fully written and ready to read)
```
root@gaebokchi:/home/rocky# nvm_vblk erase /dev/nvme0n1 0x000000000000000c
vblk:
  dev: {pmode: 'QUAD'}
  nblks: 1
  nmbytes: 16
  pos_write: 0
  pos_read: 0
  struct_nbytes: 1072
naddrs: 1
addrs:
  - addr: {ppa: 0x000000000000000c, ch: 00, lun: 00, pl: 0, blk: 0012, pg: 000, sec: 0}
nvm_vblk_erase: {elapsed: 0.0269, mb: 16.00, mbsec: 594.78}
root@gaebokchi:/home/rocky# nvm_vblk write /dev/nvme0n1 0x000000000000000c
vblk:
  dev: {pmode: 'QUAD'}
  nblks: 1
  nmbytes: 16
  pos_write: 0
  pos_read: 0
  struct_nbytes: 1072
naddrs: 1
addrs:
  - addr: {ppa: 0x000000000000000c, ch: 00, lun: 00, pl: 0, blk: 0012, pg: 000, sec: 0}
nvm_buf_alloc: {elapsed: 0.000007}
nvm_buf_fill: {elapsed: 0.017130}
nvm_vblk_write: {elapsed: 0.5231, mb: 16.00, mbsec: 30.59}
root@gaebokchi:/home/rocky#
```
And, submit read command
```
root@gaebokchi:/home/rocky#
root@gaebokchi:/home/rocky# nvm_addr read /dev/nvme0n1 0x000000000000000c
# nvm_addr_read: {pmode: QUAD}
addr: {ppa: 0x000000000000000c, ch: 00, lun: 00, pl: 0, blk: 0012, pg: 000, sec: 0}
opcode(0x92), err(-1), result(7), status(1)
naddrs: 1
addrs:
  - addr: {ppa: 0x000000000000000c, ch: 00, lun: 00, pl: 0, blk: 0012, pg: 000, sec: 0}
# nvm_addr_read: Interrupted system call
nvm_ret: {result: 0x7, status: 1}
# read: Interrupted system call
root@gaebokchi:/home/rocky#
```
the result is like above. it takes a couple of minutes to see some response. plus, the following is system log 

```
[  278.701140] nvme nvme0: I/O 652 QID 2 timeout, aborting
[  338.795897] nvme nvme0: I/O 26 QID 0 timeout, reset controller
[  338.795919] nvme nvme0: I/O 652 QID 2 timeout, reset controller
[  401.098425] nvme nvme0: Abort status: 0x7
[  401.254264] nvme nvme0: Removing after probe failure status: -19 
[  401.274085] nvme0n1: detected capacity change from 4398046507008 to 0
```
I'm using cnex ocssd board(firmware revision is R1.3).

Is there any recommendation to address this problem?

thank you.
